### ISSUE TITLE
Type Error

### ISSUE THREAD

**Issue by GabrielK7799** [niklasvieth/polestar-ios-medium-widget#14]
I received an error of the script:

2024-11-06 11:57:40: Error on line 294:27: TypeError: null is not an object (evaluating 'apiCreds.access_token')

Do you know anything about it?

**Comment by niklasvieth** [comment]
Please check again your email + password for typos and check that it they are surrounded by quotes like this

```
const POLESTAR_EMAIL = "EMAIL";
const POLESTAR_PASSWORD = "PASSWORD";
```

**Comment by GabrielK7799** [comment]
I checked them and it worked all fine tomorrow but suddenly today this error occurred
________________________________
Von: Niklas ***@***.***>
Gesendet: Wednesday, November 6, 2024 12:38:08 PM
An: niklasvieth/polestar-ios-medium-widget ***@***.***>
Cc: GabrielK7799 ***@***.***>; Author ***@***.***>
Betreff: Re: [niklasvieth/polestar-ios-medium-widget] Type Error (Issue #14)


Please check again your email + password for typos and check that it they are surrounded by quotes like this

const POLESTAR_EMAIL = "EMAIL";
const POLESTAR_PASSWORD = "PASSWORD";

**Comment by niklasvieth** [comment]
Have the same issue, will have a look into it.

```json
{"errors":[{"message":"An internal error has occured.","path":["getAuthToken"],"extensions":{"serviceName":"auth","exception":{"path":["getAuthToken"],"stacktrace":["UserInputError: An internal error has occured.","    at jZi (/var/task/src/functions/auth/handler.js:1381:2697051)","    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","    at async KZi (/var/task/src/functions/auth/handler.js:1381:2697884)","    at async getAuthToken (/var/task/src/functions/auth/handler.js:1381:2724149)"],"message":"An internal error has occured.","locations":[{"line":1,"column":44}]},"code":"BAD_USER_INPUT"}}],"data":{"getAuthToken":null}}
```

**Comment by aewilliams123** [comment]
Just to add to this that I have been facing the same issue since this morning and the error message has not disappeared yet.
