### ISSUE TITLE
Use official Polestar API

### ISSUE THREAD

**Issue by BeauGiles** [niklasvieth/polestar-ios-medium-widget#2]
Hi!
Would it be possible to look at using the official Polestar API, instead of using Tibber?

It looks like not all regions can use Tibber (ie after trying to connect my car through the Tibber app and granting permission with Polestar, Tibber returns an error - presumably because I'm in Australia, not Europe).

This 'official' API has surfaced in the last few days...

Log in at https://www.polestar.com/au/auth/login?to=/au/login/profile

Head to 'Cars' tab - https://www.polestar.com/au/login/cars 

Select your car - https://www.polestar.com/au/login/explore-car/***UUID***

<img width="859" alt="Screenshot 2023-12-16 at 09 48 17" src="https://github.com/leeyuentuen/polestar_api/assets/211889/676a2caf-48da-49b9-b9af-59fa57ff8527">

Page makes a bunch of API calls;

Battery - https://pc-api.polestar.com/eu-north-1/my-star/?query=query%20GetBatteryData(%24vin%3A%20String!)%20%7B%0A%20%20getBatteryData(vin%3A%20%24vin)%20%7B%0A%20%20%20%20averageEnergyConsumptionKwhPer100Km%0A%20%20%20%20batteryChargeLevelPercentage%0A%20%20%20%20chargerConnectionStatus%0A%20%20%20%20chargingCurrentAmps%0A%20%20%20%20chargingPowerWatts%0A%20%20%20%20chargingStatus%0A%20%20%20%20estimatedChargingTimeMinutesToTargetDistance%0A%20%20%20%20estimatedChargingTimeToFullMinutes%0A%20%20%20%20estimatedDistanceToEmptyKm%0A%20%20%20%20estimatedDistanceToEmptyMiles%0A%20%20%20%20eventUpdatedTimestamp%20%7B%0A%20%20%20%20%20%20iso%0A%20%20%20%20%20%20unix%0A%20%20%20%20%20%20__typename%0A%20%20%20%20%7D%0A%20%20%20%20__typename%0A%20%20%7D%0A%7D&operationName=GetBatteryData&variables=%7B%22vin%22%3A%22****VIN*****%22%7D

Odometer - https://pc-api.polestar.com/eu-north-1/my-star/?query=query%20GetOdometerData(%24vin%3A%20String!)%20%7B%0A%20%20getOdometerData(vin%3A%20%24vin)%20%7B%0A%20%20%20%20averageSpeedKmPerHour%0A%20%20%20%20eventUpdatedTimestamp%20%7B%0A%20%20%20%20%20%20iso%0A%20%20%20%20%20%20unix%0A%20%20%20%20%20%20__typename%0A%20%20%20%20%7D%0A%20%20%20%20odometerMeters%0A%20%20%20%20tripMeterAutomaticKm%0A%20%20%20%20tripMeterManualKm%0A%20%20%20%20__typename%0A%20%20%7D%0A%7D&operationName=GetOdometerData&variables=%7B%22vin%22%3A%22****VIN*****%22%7D

Example of the battery query result

```{
    "data": {
        "getBatteryData": {
            "averageEnergyConsumptionKwhPer100Km": 16,
            "batteryChargeLevelPercentage": 90,
            "chargerConnectionStatus": "CHARGER_CONNECTION_STATUS_DISCONNECTED",
            "chargingCurrentAmps": null,
            "chargingPowerWatts": null,
            "chargingStatus": "CHARGING_STATUS_IDLE",
            "estimatedChargingTimeMinutesToTargetDistance": null,
            "estimatedChargingTimeToFullMinutes": 0,
            "estimatedDistanceToEmptyKm": 340,
            "estimatedDistanceToEmptyMiles": 210,
            "eventUpdatedTimestamp": {
                "iso": "2023-12-15T22:32:14.000Z",
                "unix": "1702679534",
                "__typename": "EventUpdatedTimestamp"
            },
            "__typename": "Battery"
        }
    }
}

**Comment by niklasvieth** [comment]
Will check it out, for authorization still no official way. Website uses oAuth code flow to get the Bearer token.

**Comment by niklasvieth** [comment]
Seems like there might be a way soon.

https://github.com/leeyuentuen/polestar_api/issues/10#issuecomment-1861778900

**Comment by niklasvieth** [comment]
Tested the authentication used here and works 🥳 
Will start implementing this into the widget soon.
https://github.com/andysmithfal/polestar.js

**Comment by niklasvieth** [comment]
@BeauGiles I updated the [lockscreen widget](https://github.com/niklasvieth/polestar-ios-lockscreen-widget) to work with the Polestar API, the medium widget will follow soon. Want to display some more info during charging but still working on the layout.

**Comment by BeauGiles** [comment]
> @BeauGiles I updated the [lockscreen widget](https://github.com/niklasvieth/polestar-ios-lockscreen-widget) to work with the Polestar API, the medium widget will follow soon. Want to display some more info during charging but still working on the layout.

Thank you - works brilliantly!

(and of course works for me down under in Australia, whereas I could never get Tibber to work after granting access in the Tibber app > Polestar login > Tibber app errored - looking forward to the medium widget)

**Comment by BeauGiles** [comment]
> @BeauGiles I updated the [lockscreen widget](https://github.com/niklasvieth/polestar-ios-lockscreen-widget) to work with the Polestar API, the medium widget will follow soon. Want to display some more info during charging but still working on the layout.

Hello! Hope you've had a merry Christmas and new years - any chance you have had any luck sharing an updated medium layout widget? :) 

Also... just flagging that it looks like 2FA is coming to the Polestar site which may end up breaking these widgets... for a bit. https://github.com/andysmithfal/polestar.js/issues/2

**Comment by MaXeraph** [comment]
If it helps anyone temporarily, I hacked together a Frankenstein gist here utilizing the new V2 login code and it should work for the time being! (probably before the 2FA kicks in)

https://gist.github.com/MaXeraph/0c393e15d4b3d17fc998949716faa975

This is just a quick hack to get it working. All credit belongs to @niklasvieth

**Comment by niklasvieth** [comment]
Sorry guys didn’t have the time to far to finish what I started, but updated version will come this week!

**Comment by niklasvieth** [comment]
@BeauGiles as promised :) new version of the widget available, update possible via script dude if you installed it that way. 
also some new features and config options are now available
