### ISSUE TITLE
Vin error

### ISSUE THREAD

**Issue by Nilasstoumann** [niklasvieth/polestar-ios-medium-widget#6]
Hi Niklas,
I keep getting an error, trying to run your script.
Either the error is, that the VIN is unidentified (I have only one car, so it shouldnt be necessary to write) - Or the error (if I write the VIN number) is no vehicle found with that VIN..

any guesses to what the error is?
I have a Polestar profile, and Tibber

**Comment by niklasvieth** [comment]
If you login to https://www.polestar.com does your vehicle show up in your profile and does it show the battery status?

**Comment by Nilasstoumann** [comment]
Hi Niklas,

That was the problem, and are now fixed - I have now your script working as a beautiful widget!

Great work - and thank you 😊
