### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by BRISTOLMAN** [niklasvieth/polestar-ios-medium-widget#7]
Hi
Iv done all the stages and have just added email and password into the script, then i press play button it brings up the following error.

Exception Occurred
Error on line 284:33:
TypeError: undefined is not an object (evaluating
'response.data.getAuthToken

any ideas.

iv copied the script and only added email and password in correct locations.

thanks
Tom

**Comment by niklasvieth** [comment]
Does the car and the battery status show up if you login to polestar.com in your account?
