### ISSUE TITLE
Any plans for a small widget?

### ISSUE THREAD

**Issue by Lunkobelix** [niklasvieth/polestar-ios-medium-widget#9]
Sorry for posting this as an issue, which it isn't :) Didn't find another way to reach out. Any plans for a small (1x1) widget for the iOS home screen, so basically half the size fo the current one? Would fit my setup a lot better.

This looks amazing, btw!

**Comment by wabj** [comment]
I second this. The SOC widget is brilliant, it would be good to have a small widget as well. Thanks for putting this together

**Comment by Lunkobelix** [comment]
Now we’re talking - beautiful! Thanks for looking into it 😀
Would it work to have an option to replace “220 km” with the car image?

**Comment by wabj** [comment]
This is Perfect!I’m not too worried about the image of the car ☺️I hope Polestar add features to the app similar to Tesla. Sent from my iPhone.On 10 Apr 2024, at 20:37, Niklas ***@***.***> wrote:﻿
Hey @wabj @Lunkobelix,
Thanks for the feedback!
I will check it out! Is something like that what you would expect?
image.png (view on web)
I think the car image would make it a bit crowded.

**Comment by niklasvieth** [comment]
@Lunkobelix probably something similar to what Tesla did?

![image](https://github.com/niklasvieth/polestar-ios-medium-widget/assets/41342090/babd41c2-339a-47f2-808b-45a8b9013652)

Let me see if I find some time on the weekend to play around a bit with the layout.

**Comment by wabj** [comment]
Agreed. It’s brilliant 🤩 Sent from my iPhone.On 10 Apr 2024, at 21:05, Lunkobelix ***@***.***> wrote:﻿
Keep it simple, I’m just happy if I get a smaller widget 😀 I like your design and how clean it looks.

**Comment by niklasvieth** [comment]
Hi @wabj @Lunkobelix intermediate update, will release the repo and instructions for the small widget most likely tomorrow :)

<img width="323" alt="image" src="https://github.com/niklasvieth/polestar-ios-medium-widget/assets/41342090/61c58bf1-ece5-49bb-bb0b-21a1f79a8b2b">

**Comment by Lunkobelix** [comment]
Love it - looks stunning! 😀

**Comment by wabj** [comment]
This is stunning, Thanks so much!

**Comment by niklasvieth** [comment]
Not available see https://github.com/niklasvieth/polestar-ios-small-widget for intructions

**Comment by wabj** [comment]
thank you so much
